//! Compose-local database preparation and deterministic demo seeding.
//!
//! This module implements the `agentics-local-demo` binary used by the
//! containerized development stack. Compose owns service lifetimes, networking,
//! Postgres storage, and log collection. This binary only applies database
//! migrations and writes deterministic fake challenge/submission data once the
//! configured API and database are reachable.

use std::collections::HashMap;
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::time::Duration;

use agentics_config::{
    DEFAULT_API_HOST, DEFAULT_API_PORT, ENV_AGENTICS_API_BASE_URL, default_local_api_base_url,
};
use clap::{Parser, Subcommand};
use secrecy::{ExposeSecret, SecretString};
use sqlx::postgres::PgPoolOptions;
use url::Url;
use zip::CompressionMethod;
use zip::write::SimpleFileOptions;

mod local_demo_config;
use local_demo_config::{
    DemoDatabaseName, env_value, file_env_non_empty, load_dotenv_file, parse_url, repo_root,
    resolve_demo_database_url, validate_demo_database_url,
};

mod local_demo_seed;

use crate::support::{ReportLine, SupportError, env_non_empty, print_reports, run_with_ctrl_c};

const PREFIX: &str = "agentics-demo";
const ENV_DEMO_ENV_FILE: &str = "AGENTICS_DEMO_ENV_FILE";
const ENV_DEMO_DATABASE_NAME: &str = "AGENTICS_DEMO_DATABASE_NAME";
const ENV_DEMO_DATABASE_URL: &str = "AGENTICS_DEMO_DATABASE_URL";
const ENV_DEMO_DATABASE_URL_CONFIRM: &str = "AGENTICS_DEMO_DATABASE_URL_CONFIRM";
const ENV_STORAGE_ROOT: &str = "AGENTICS_STORAGE_ROOT";
const ENV_DATABASE_URL: &str = "AGENTICS_DATABASE_URL";

const DEFAULT_DEMO_DATABASE_NAME: &str = "agentics_demo";
const NON_LOOPBACK_DATABASE_CONFIRMATION: &str = "non-loopback-demo-db";
const DEMO_ARTIFACT_IDS: &[&str] = &[
    "20000000-0000-4000-8000-000000000001",
    "20000000-0000-4000-8000-000000000002",
    "20000000-0000-4000-8000-000000000003",
    "20000000-0000-4000-8000-000000000101",
    "20000000-0000-4000-8000-000000000102",
    "20000000-0000-4000-8000-000000000103",
];
const DEMO_ARTIFACT_FILES: &[DemoArtifactFile] = &[
    DemoArtifactFile {
        path: "agentics.solution.json",
        executable: false,
        contents: br#"{"protocol":"zip_project","protocol_version":1,"note":"Local demo artifact.","commands":{"setup":"setup.sh","run":"run.sh"}}"#,
    },
    DemoArtifactFile {
        path: "README.md",
        executable: false,
        contents: b"# Local Demo Submission\n\nGenerated by agentics-local-demo.\n",
    },
    DemoArtifactFile {
        path: "setup.sh",
        executable: true,
        contents: b"#!/usr/bin/env sh\nset -eu\necho demo setup\n",
    },
    DemoArtifactFile {
        path: "run.sh",
        executable: true,
        contents: b"#!/usr/bin/env sh\nset -eu\npython main.py\n",
    },
    DemoArtifactFile {
        path: "main.py",
        executable: false,
        contents: b"import json, sys\npayload=json.load(sys.stdin)\nprint(json.dumps({'answer': payload.get('a', 0) + payload.get('b', 0)}))\n",
    },
];

struct DemoArtifactFile {
    path: &'static str,
    executable: bool,
    contents: &'static [u8],
}

/// CLI for Compose-local database preparation.
#[derive(Debug, Parser)]
#[command(
    about = "Prepares the Agentics Compose dev database.",
    long_about = "Applies migrations or seeds deterministic demo data for the containerized development stack. It does not start Postgres, API, worker, web, or Docker runner services; Compose owns those lifetimes."
)]
pub struct Cli {
    #[command(subcommand)]
    command: LocalDemoCommand,
}

/// Compose-local database command.
#[derive(Debug, Subcommand)]
pub enum LocalDemoCommand {
    /// Run migrations against the configured demo database.
    Migrate,
    /// Re-run demo seeding against an existing database and API.
    Seed,
}

/// Run this command from process args and env.
pub async fn run_from_process() -> ExitCode {
    let cli = Cli::parse();
    run_with_ctrl_c(PREFIX, async move {
        match run(cli).await {
            Ok(reports) => print_reports(PREFIX, &reports),
            Err(error) => {
                eprintln!("[{PREFIX}] ERROR: {error}");
                ExitCode::from(2)
            }
        }
    })
    .await
}

async fn run(cli: Cli) -> Result<Vec<ReportLine>, LocalDemoError> {
    let config = LocalDemoConfig::from_env()?;
    match cli.command {
        LocalDemoCommand::Migrate => migrate_only(&config).await,
        LocalDemoCommand::Seed => seed_only(&config).await,
    }
}

async fn migrate_only(config: &LocalDemoConfig) -> Result<Vec<ReportLine>, LocalDemoError> {
    wait_for_database(config).await?;
    run_migrations(config).await?;
    Ok(vec![ReportLine::pass(
        "migrate",
        "applied database migrations",
    )])
}

async fn seed_only(config: &LocalDemoConfig) -> Result<Vec<ReportLine>, LocalDemoError> {
    wait_for_database(config).await?;
    wait_for_http("API", &config.health_url()?).await?;
    seed_database(config).await
}

#[derive(Debug, Clone)]
pub struct LocalDemoConfig {
    repo_root: PathBuf,
    storage_root: PathBuf,
    database_url: SecretString,
    api_base_url: Url,
}

fn resolve_env_file(repo_root: &Path) -> PathBuf {
    env_non_empty(ENV_DEMO_ENV_FILE)
        .map(PathBuf::from)
        .unwrap_or_else(|| repo_root.join("deploy/compose/env/dev.env.example"))
}

fn resolve_database_name(
    file_env: &HashMap<String, String>,
) -> Result<DemoDatabaseName, LocalDemoError> {
    DemoDatabaseName::parse(
        &env_value(ENV_DEMO_DATABASE_NAME, file_env)
            .unwrap_or_else(|| DEFAULT_DEMO_DATABASE_NAME.to_string()),
    )
}

fn resolve_database_url(
    database_name: &DemoDatabaseName,
    file_env: &HashMap<String, String>,
) -> Result<Url, LocalDemoError> {
    let database_url_raw = resolve_demo_database_url(
        env_non_empty(ENV_DEMO_DATABASE_URL),
        file_env_non_empty(ENV_DEMO_DATABASE_URL, file_env),
    )?;
    validate_demo_database_url(
        &database_url_raw,
        database_name,
        env_value(ENV_DEMO_DATABASE_URL_CONFIRM, file_env).as_deref(),
    )
}

fn resolve_api_base_url(file_env: &HashMap<String, String>) -> Result<Url, LocalDemoError> {
    parse_url(
        ENV_AGENTICS_API_BASE_URL,
        &env_value(ENV_AGENTICS_API_BASE_URL, file_env)
            .unwrap_or_else(|| default_local_api_base_url(DEFAULT_API_HOST, DEFAULT_API_PORT)),
    )
}

fn resolve_storage_root(repo_root: &Path, file_env: &HashMap<String, String>) -> PathBuf {
    let storage_root = env_value(ENV_STORAGE_ROOT, file_env)
        .map(PathBuf::from)
        .unwrap_or_else(|| repo_root.join(".agentics-compose/dev/storage"));
    if storage_root.is_absolute() {
        storage_root
    } else {
        repo_root.join(storage_root)
    }
}

impl LocalDemoConfig {
    fn from_env() -> Result<Self, LocalDemoError> {
        let repo_root = repo_root()?;
        let env_file = resolve_env_file(&repo_root);
        let file_env = load_dotenv_file(&env_file)?;
        let database_name = resolve_database_name(&file_env)?;
        let database_url = resolve_database_url(&database_name, &file_env)?;
        let api_base_url = resolve_api_base_url(&file_env)?;
        let storage_root = resolve_storage_root(&repo_root, &file_env);
        Ok(Self {
            repo_root,
            storage_root,
            database_url: SecretString::from(database_url.to_string()),
            api_base_url,
        })
    }

    fn health_url(&self) -> Result<Url, LocalDemoError> {
        self.api_base_url
            .join("healthz")
            .map_err(|error| LocalDemoError::InvalidConfig(format!("invalid health URL: {error}")))
    }
}

async fn wait_for_database(config: &LocalDemoConfig) -> Result<(), LocalDemoError> {
    let deadline = deadline_after(Duration::from_secs(60));
    loop {
        if PgPoolOptions::new()
            .max_connections(1)
            .connect(config.database_url.expose_secret())
            .await
            .is_ok()
        {
            return Ok(());
        }
        if tokio::time::Instant::now() > deadline {
            return Err(LocalDemoError::Timeout("Postgres readiness".to_string()));
        }
        tokio::time::sleep(Duration::from_secs(1)).await;
    }
}

async fn run_migrations(config: &LocalDemoConfig) -> Result<(), LocalDemoError> {
    let pool = PgPoolOptions::new()
        .max_connections(5)
        .connect(config.database_url.expose_secret())
        .await?;
    let migrations = config.repo_root.join("backend/migrations");
    let migrator = sqlx::migrate::Migrator::new(migrations)
        .await
        .map_err(|error| LocalDemoError::Migrate(error.to_string()))?;
    migrator
        .run(&pool)
        .await
        .map_err(|error| LocalDemoError::Migrate(error.to_string()))?;
    Ok(())
}

async fn seed_database(config: &LocalDemoConfig) -> Result<Vec<ReportLine>, LocalDemoError> {
    write_demo_artifacts(config)?;
    let pool = PgPoolOptions::new()
        .max_connections(3)
        .connect(config.database_url.expose_secret())
        .await?;
    local_demo_seed::seed_database(&pool).await?;
    pool.close().await;
    Ok(vec![
        ReportLine::pass("demo artifacts", "wrote sample solution ZIPs"),
        ReportLine::pass(
            "demo seed",
            "inserted local-demo service heartbeat evidence",
        ),
    ])
}

fn write_demo_artifacts(config: &LocalDemoConfig) -> Result<(), LocalDemoError> {
    let artifact_dir = config.storage_root.join("solution-submissions");
    std::fs::create_dir_all(&artifact_dir)?;
    for id in DEMO_ARTIFACT_IDS {
        write_demo_artifact(&artifact_dir.join(format!("{id}.zip")))?;
    }
    Ok(())
}

fn write_demo_artifact(path: &Path) -> Result<(), LocalDemoError> {
    let file = File::create(path)?;
    let mut archive = zip::ZipWriter::new(file);
    for entry in DEMO_ARTIFACT_FILES {
        archive.start_file(entry.path, demo_artifact_file_options(entry.executable))?;
        archive.write_all(entry.contents)?;
    }
    archive.finish()?;
    Ok(())
}

fn demo_artifact_file_options(executable: bool) -> SimpleFileOptions {
    SimpleFileOptions::default()
        .compression_method(CompressionMethod::Deflated)
        .unix_permissions(if executable { 0o755 } else { 0o644 })
}

async fn wait_for_http(label: &str, url: &Url) -> Result<(), LocalDemoError> {
    let client = reqwest::Client::new();
    let deadline = deadline_after(Duration::from_secs(180));
    loop {
        if let Ok(response) = client.get(url.clone()).send().await
            && response.status().is_success()
        {
            return Ok(());
        }
        if tokio::time::Instant::now() > deadline {
            return Err(LocalDemoError::Timeout(format!("{label} at {url}")));
        }
        tokio::time::sleep(Duration::from_secs(1)).await;
    }
}

fn deadline_after(duration: Duration) -> tokio::time::Instant {
    tokio::time::Instant::now()
        .checked_add(duration)
        .unwrap_or_else(tokio::time::Instant::now)
}

/// Local demo orchestration error.
#[derive(Debug, thiserror::Error)]
pub enum LocalDemoError {
    #[error(transparent)]
    Support(#[from] SupportError),
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    Dotenv(#[from] dotenvy::Error),
    #[error(transparent)]
    Sqlx(#[from] sqlx::Error),
    #[error(transparent)]
    Zip(#[from] zip::result::ZipError),
    #[error(transparent)]
    Service(#[from] agentics_domain::error::ServiceError),
    #[error("invalid local demo config: {0}")]
    InvalidConfig(String),
    #[error("{0} timed out")]
    Timeout(String),
    #[error("migration failed: {0}")]
    Migrate(String),
}

#[cfg(test)]
mod tests {
    use std::fs::File;
    use std::io::Read;

    use super::{
        DemoDatabaseName, ENV_DEMO_DATABASE_URL, NON_LOOPBACK_DATABASE_CONFIRMATION,
        resolve_demo_database_url, validate_demo_database_url, write_demo_artifact,
    };

    /// Verifies database names are constrained before SQL identifier use.
    #[test]
    fn database_name_rejects_unsafe_identifier() {
        assert!(DemoDatabaseName::parse("agentics_demo").is_ok());
        assert!(DemoDatabaseName::parse("agentics-demo").is_err());
        assert!(DemoDatabaseName::parse("demo;drop").is_err());
    }

    /// Verifies local demo refuses implicit or generic platform database URLs.
    #[test]
    fn demo_database_url_must_be_explicit() {
        let error = resolve_demo_database_url(None, None).expect_err("missing URL should fail");
        assert!(error.to_string().contains(ENV_DEMO_DATABASE_URL));
    }

    /// Verifies demo database URLs must target the demo database on loopback by default.
    #[test]
    fn demo_database_url_is_validated() {
        let name = DemoDatabaseName::parse("agentics_demo").unwrap();
        assert!(
            validate_demo_database_url(
                "postgres://agentics:agentics@127.0.0.1:5432/agentics_demo",
                &name,
                None,
            )
            .is_ok()
        );
        assert!(
            validate_demo_database_url(
                "postgres://agentics:agentics@127.0.0.1:5432/agentics",
                &name,
                None,
            )
            .is_err()
        );
        assert!(
            validate_demo_database_url(
                "postgres://agentics:agentics@db.internal:5432/agentics_demo",
                &name,
                None,
            )
            .is_err()
        );
        assert!(
            validate_demo_database_url(
                "postgres://agentics:agentics@db.internal:5432/agentics_demo",
                &name,
                Some(NON_LOOPBACK_DATABASE_CONFIRMATION),
            )
            .is_ok()
        );
    }

    /// Verifies generated demo ZIPs contain the runnable solution contract.
    #[test]
    fn demo_artifact_zip_contains_solution_files() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let path = tempdir.path().join("artifact.zip");
        write_demo_artifact(&path).expect("write demo artifact");
        let file = File::open(path).expect("open demo artifact");
        let mut archive = zip::ZipArchive::new(file).expect("read demo artifact");

        let mut manifest = String::new();
        archive
            .by_name("agentics.solution.json")
            .expect("manifest exists")
            .read_to_string(&mut manifest)
            .expect("read manifest");
        assert!(manifest.contains("\"protocol\":\"zip_project\""));
        assert!(archive.by_name("setup.sh").is_ok());
        assert!(archive.by_name("run.sh").is_ok());
        assert!(archive.by_name("main.py").is_ok());
    }
}
