import { challengeDetailResponseSchema as generatedChallengeDetailResponseSchema } from "@/lib/generated/schemas";

export type {
  AdminCapacityResponse,
  AdminChallengeListItem,
  AdminChallengeListResponse,
  AdminChallengePrivateAssetListResponse,
  AdminLoginRequest,
  AdminServiceHeartbeatListResponse,
  AdminSessionResponse,
  AdminSolutionSubmissionListItem,
  AdminSolutionSubmissionListResponse,
  ChallengeAdminResponse,
  ChallengeDetailResponse,
  ChallengeDraftCleanupResponse,
  ChallengeDraftListItem,
  ChallengeDraftListResponse,
  ChallengeDraftResponse,
  ChallengeListResponse,
  ChallengePrivateAssetResponse,
  ChallengeShortlistResponse,
  ChallengeShortlistRevisionResponse,
  CreateChallengeDraftRequest,
  CreateChallengeShortlistRevisionRequest,
  CreatePioneerCodeRequest,
  CreatorChallengeDraftResponse,
  CreatorChallengeParticipantsResponse,
  CreatorChallengeStatsResponse,
  CreatorMeResponse,
  CreatorSessionResponse,
  DisableAgentResponse,
  EvaluationJobResponse,
  GithubOauthCallbackRequest,
  GithubOauthLoginRequest,
  GithubOauthLoginResponse,
  LeaderboardResponse,
  PioneerCodeDetailResponse,
  PioneerCodeListResponse,
  PublicSolutionSubmissionListResponse,
  PublicStatsResponse,
  PublishChallengeResponse,
  RankingContextResponse,
  RegisterAgentRequest,
  ReviewChallengeDraftRequest,
  RevokePioneerCodeResponse,
  ScoreDistributionResponse,
  SolutionSubmissionArtifactResponse,
  SolutionSubmissionLogsResponse,
  SolutionSubmissionResponse,
  SolutionSubmissionResultReportResponse,
  UploadChallengePrivateAssetRequest,
  ValidateChallengeDraftRequest,
} from "@/lib/generated/schemas";

export {
  adminCapacityResponseSchema,
  adminChallengeListResponseSchema,
  adminChallengePrivateAssetListResponseSchema,
  adminLoginRequestSchema,
  adminServiceHeartbeatListResponseSchema,
  adminSessionResponseSchema,
  adminSolutionSubmissionListResponseSchema,
  challengeAdminResponseSchema,
  challengeDraftCleanupResponseSchema,
  challengeDraftListResponseSchema,
  challengeDraftResponseSchema,
  challengeListResponseSchema,
  challengePrivateAssetResponseSchema,
  challengeShortlistResponseSchema,
  challengeShortlistRevisionResponseSchema,
  createChallengeDraftRequestSchema,
  createChallengeShortlistRevisionRequestSchema,
  createPioneerCodeRequestSchema,
  creatorChallengeDraftResponseSchema,
  creatorChallengeParticipantsResponseSchema,
  creatorChallengeStatsResponseSchema,
  creatorMeResponseSchema,
  creatorSessionResponseSchema,
  disableAgentResponseSchema,
  evaluationJobResponseSchema,
  githubOauthCallbackRequestSchema,
  githubOauthLoginRequestSchema,
  githubOauthLoginResponseSchema,
  leaderboardResponseSchema,
  pioneerCodeDetailResponseSchema,
  pioneerCodeListResponseSchema,
  publicSolutionSubmissionListResponseSchema,
  publicStatsResponseSchema,
  publishChallengeResponseSchema,
  rankingContextResponseSchema,
  registerAgentRequestSchema,
  reviewChallengeDraftRequestSchema,
  revokePioneerCodeResponseSchema,
  scoreDistributionResponseSchema,
  solutionSubmissionArtifactResponseSchema,
  solutionSubmissionLogsResponseSchema,
  solutionSubmissionResponseSchema,
  solutionSubmissionResultReportResponseSchema,
  uploadChallengePrivateAssetRequestSchema,
  validateChallengeDraftRequestSchema,
} from "@/lib/generated/schemas";

export const challengeDetailResponseSchema =
  generatedChallengeDetailResponseSchema.superRefine((response, ctx) => {
    const mode = response.spec.execution.mode;
    response.spec.targets.forEach((target, index) => {
      const hasSolutionRun = target.resource_profile.solution.run !== undefined;
      if (mode === "coexecuted_benchmark" && hasSolutionRun) {
        ctx.addIssue({
          code: "custom",
          path: [
            "spec",
            "targets",
            index,
            "resource_profile",
            "solution",
            "run",
          ],
          message:
            "solution.run is forbidden for coexecuted_benchmark execution",
        });
      }
      if (mode !== "coexecuted_benchmark" && !hasSolutionRun) {
        ctx.addIssue({
          code: "custom",
          path: [
            "spec",
            "targets",
            index,
            "resource_profile",
            "solution",
            "run",
          ],
          message: `solution.run is required for ${mode} execution`,
        });
      }
    });
  });
